Updates build scripts.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -2,15 +2,224 @@
 
 set -e
 
-bundle install
+install_homebrew ()
+{
+  if [ -z $GITHUB_ACCESS_TOKEN ]
+  then
+    export HOMEBREW_GITHUB_API_TOKEN=$GITHUB_ACCESS_TOKEN
+  fi
 
-if [ -z "$GITHUB_ACCESS_TOKEN" ]
-then
-  carthage bootstrap
-else
-  echo "-> Installing forked version of carthage"
+  if type brew > /dev/null
+  then
+    echo "    ✔ brew is already installed"
+    echo ""
+    echo " → Updating homebrew formulas"
+    brew update > /dev/null
+    echo "    ✔ formulas updated"
+  else
+    command -v ruby >/dev/null 2>&1 || { echo >&2 "Error: Some ruby of version is required to install homebrew. Aborting"; exit 1; }
+    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  fi
+}
+
+# param $1 formula name
+# param $2 [optional] tap path
+brew_install ()
+{
+  formula_version=`brew list --versions $1`
+  if [ -z "$formula_version" ]
+  then
+    if [ -z $2 ]
+    then
+      formula_name=$1
+    else
+      formula_name="$2/$1"
+    fi
+    echo ""
+    echo " → Installing brew formula $formula_name"
+    brew install -v $formula_name > /dev/null 2>&1
+
+    # Extract version
+    regexp="^.*([0-9]\.[0-9]\.[0-9]).*$"
+    installed_version=""
+    eval "output=\"$(brew info $1)\""
+    if [[ $output =~ $regexp ]]
+    then
+      installed_version=${BASH_REMATCH[1]}
+    fi
+
+    echo "    ✔ $formula_name $installed_version has been installed"
+  else
+    echo "    ✔ $1 is already installed"
+  fi
+}
+
+print_gem_install_cmd ()
+{
+  regexp="gem ['\"]([a-zA-Z0-9_-]+)['\"](,.*)?"
+  gems=""
+  while read -r line
+  do
+    if [[ $line =~ $regexp ]]
+    then
+      gems="$gems ${BASH_REMATCH[1]}"
+    fi
+  done < Gemfile
+
   echo ""
-  sudo installer -pkg script/Carthage.pkg -target /
+  echo "  $> 'sudo gem install$gems'"
+  echo ""
+}
 
-  carthage bootstrap --github-access-token "$GITHUB_ACCESS_TOKEN"
-fi
+bundle_install ()
+{
+  echo ""
+  echo " → Installing gems"
+  echo ""
+  if type bundle > /dev/null
+  then
+    bundle install
+  else
+    # TODO ask user if he/she wants the script to try to install
+    # rbenv, ruby and bundler.
+    printf "\033[1;33m⚠ WARNING: Ruby gems in Gemfile could not be installed because 'bundler' is not available.\n" \
+           "You should install rbenv or rvm and bundler" \
+           "or try to install the gems globally by running the following command:"
+    print_gem_install_cmd
+    printf "\033[0m"
+  fi
+}
+
+install_git_hooks ()
+{
+  echo ""
+  echo " → Installing git hooks"
+  echo ""
+  for hook in script/git_hooks/*
+  do
+    cp $hook .git/hooks
+    echo "    ✔ $hook successfully installed"
+  done
+  echo ""
+}
+
+bootstrap_carthage ()
+{
+  echo ""
+  echo " → Bootstrapping Carthage"
+  echo ""
+  if [ -z $GITHUB_ACCESS_TOKEN ]
+  then
+    time carthage bootstrap --platform ios --use-ssh
+  else
+    time carthage bootstrap --platform ios --use-ssh --github-access-token $GITHUB_ACCESS_TOKEN
+  fi
+}
+
+bootstrap_cocoapods ()
+{
+  echo ""
+  echo " → Bootstrapping Cocoapods"
+  echo ""
+  if type bundle > /dev/null && bundle show pod > /dev/null
+  then
+    bundle exec pod install
+  else
+    pod install
+  fi
+}
+
+echo_submodule_name ()
+{
+  echo "  ✔ $name successfully initialized"
+}
+
+init_submodules ()
+{
+  echo ""
+  echo " → Initializing submodules ..."
+  echo ""
+  git submodule update --quiet --init --recursive > /dev/null
+  git submodule foreach --quiet echo_submodule_name
+}
+
+install_carthage ()
+{
+  if [ -z $GITHUB_ACCESS_TOKEN ]
+  then
+    brew_install "carthage"
+  else
+    echo ""
+    echo " → Installing custom version of Carthage"
+    curl -s -o script/Carthage.pkg https://raw.githubusercontent.com/guidomb/ios-scripts/master/artifacts/Carthage.pkg
+    sudo installer -pkg script/Carthage.pkg -target / > /dev/null
+    echo "    ✔ Custom Carthage installed"
+  fi
+}
+
+install_dependencies ()
+{
+  echo ""
+  echo " → Installing dependencies"
+  echo ""
+  install_homebrew
+  brew_install "xcode-coveralls" "macmade/tap"
+
+  if [ -f script/script_hooks/bootstrap ]
+  then
+    script/script_hooks/bootstrap
+  fi
+}
+
+main ()
+{
+  source script/.env
+
+  echo ""
+  echo " Bootstrapping $PROJECT_NAME"
+  echo ""
+
+  install_git_hooks
+  install_dependencies
+
+  if [ -f Cartfile ]
+  then
+    install_carthage
+    bootstrap_carthage
+  fi
+
+  if [ -f Gemfile ]
+  then
+    bundle_install
+  fi
+
+  if [ -f Podfile ]
+  then
+    bootstrap_cocoapods
+  fi
+
+  if [ -f .gitmodules ]
+  then
+    init_submodules
+  fi
+
+  echo ""
+  echo " $PROJECT_NAME successfully bootstrapped"
+  echo ""
+  echo " Usefull scripts:"
+  echo ""
+  echo "  * 'script/test' to run tests."
+  echo "  * 'script/build' to build the project."
+  echo "  * 'script/update' to update project's dependencies."
+  echo ""
+  echo " You can start hacking by executing:"
+  echo ""
+  echo "    open $XCODE_PROJECT"
+  echo ""
+}
+
+export -f init_submodules
+export -f echo_submodule_name
+export -f brew_install
+
+main
diff --git a/script/coverage b/script/coverage
--- a/script/coverage
+++ b/script/coverage
@@ -1,31 +1,27 @@
-#!/bin/sh
+#!/bin/bash
 
-coverage_folder="./coverage"
+set -e
 
-if [ -z "$SKIP_COVERAGE_GENERATION" ]
+source script/.env
+
+if type xcode-coveralls > /dev/null
 then
-  echo "*** Generating coverage files ***"
-  swiftcov generate --output $coverage_folder \
-    xcodebuild -scheme ReactiveArray -project ReactiveArray.xcodeproj \
-    -sdk iphonesimulator -configuration Debug test
-else
-  echo "WARN: Coverage files genration skipped"
-fi
+  if [ ! -f script/xcenv.sh ]
+  then
+    # Running the test generates the xcenv.sh
+    script/test
+  fi
 
-if [ "$1" = "upload" ]
-then
-  echo ""
-  echo ""
-  echo "*** Uploading coverage report to Coveralls.io ***"
-  bundle exec coveralls-gcov --repo-token "$COVERALLS_TOKEN" \
-    --no-gcov -e Carthage -e Carthage,ReactiveArrayTests
-else
-  echo ""
-  echo ""
-  echo "*** Generating HTML coverage report ***"
-  gcovr -v -r ../ \
-    -e "^.*/ReactiveArray/Carthage/.*\.swift$" \
-    -e "^.*/ReactiveArray/ReactiveArrayTests/.*\.swift$" \
-    --use-gcov-files --html --html-details \
-    --output $coverage_folder/index.html --keep
+  if [ -f script/xcenv.sh ]
+  then
+    source script/xcenv.sh
+    declare -r DIR_BUILD="${OBJECT_FILE_DIR_normal}/${CURRENT_ARCH}/"
+    xcode-coveralls --include $SRCROOT --exclude "$SRCROOT""Tests" --exclude Carthage --exclude Pods --token $COVERALLS_TOKEN "${DIR_BUILD}"
+  else
+    # TODO print instruction of how to add the generation of xcenv.sh
+    echo ""
+    echo " Error: script/xcenv.sh was not generated after running 'script/test'."
+    echo ""
+    exit 1
+  fi
 fi
