Updates build scripts.

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -45,6 +45,13 @@ then
 else
   source script/.env
 
+  if [ -z "$current_schemes" ]
+  then
+    echo ""
+    echo "ERROR: There are no schemes. Probably you forgot to share your schemes"
+    exit 1
+  fi
+
   for scheme in $(schemes)
   do
     build_using_xcodebuild $scheme
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -38,7 +38,15 @@ run_tests ()
   eval $test_command
 }
 
-for scheme in $(schemes)
+current_schemes=$(schemes)
+if [ -z "$current_schemes" ]
+then
+  echo ""
+  echo "ERROR: There are no schemes. Probably you forgot to share your schemes"
+  exit 1
+fi
+
+for scheme in current_schemes
 do
   run_tests $scheme
 done
